apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-gibw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-gibw@sha256:cc1c206e99472865177a4ba47042ce1dab44c856c04c182355f63d3890a2f28c
        name: my-python
        resources: {}
status: {}
